language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]

before_install:   
  - npm install -g firebase-tools
  - cd $TRAVIS_BUILD_DIR/  
  - |
    if [ $TRAVIS_BRANCH = "master" ]; then
      firebase use chatty      
    else
      firebase use production
    fi

    firebase functions:config:get > front/src/config/runtimeconfig.json
  
install:  
jobs:
  include:
    - stage: install
      script: 
        - cd $TRAVIS_BUILD_DIR/functions/      
        - npm install
    - script: 
        - cd $TRAVIS_BUILD_DIR/front/  
        - npm install
    - stage: front build
      script: 
        - npm run build  
before_deploy:
  - cd $TRAVIS_BUILD_DIR/backend/  

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
