language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]

before_install:   
  - npm install -g firebase-tools
  - cd $TRAVIS_BUILD_DIR/  
  - if [ $TRAVIS_BRANCH = "master" ]; then
      - firebase use chatty
    else
      - firebase use production
    fi
  
install:  
jobs:
  include:
    - stage: install
      script: 
        - cd $TRAVIS_BUILD_DIR/functions/      
        - npm install
    - script: 
        - cd $TRAVIS_BUILD_DIR/front/  
        - npm install
    - stage: install2
      script: 
        - echo $TRAVIS_BRANCH
script:

before_deploy:

after_success:

