language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]


jobs:
  include:
    - stage: test1
      script: 
       - if [ true ]; then
           echo $TRAVIS_BUILD_NUMBER
         fi
    - script: 
        - echo $TRAVIS_TAG
    - stage: test2
      script: 
        - echo $TRAVIS_BRANCH
before_install: >  
  if  [ 1 = 1 ]; then
      echo "succes!";      
    else
      echo "else";
  fi
install:  

script:

before_deploy:

after_success:

