language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  

#[skip <빌드스킵>]

jobs:
  include:    
    - script: 
        - npm install -g firebase-tools 
    - script: 
        - cd $TRAVIS_BUILD_DIR/functions/    
        - npm install        
    - script: 
        - cd $TRAVIS_BUILD_DIR/front/  
        - npm install

#before_install:  
#install:  

script:
  - cd $TRAVIS_BUILD_DIR/front/  
  - npm run build

before_deploy:
  - cd $TRAVIS_BUILD_DIR/  
  
after_success:
  - firebase deploy --token $FIREBASE_TOKEN    

#https://docs.travis-ci.com/user/deployment/firebase/#generating-your-firebase-token

# notifications:
#   email:
#     recipients:
#       - jojoldu@gmail.com
    