language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]

before_install: 
  - npm install -g firebase-tools

install:  
jobs:
  include:
    - stage: install
      script: 
        - cd $TRAVIS_BUILD_DIR/functions/      
        - npm install
    - script: 
        - cd $TRAVIS_BUILD_DIR/front/  
        - npm install
        - if [ $TRAVIS_BRANCH = "master" ]; then
              echo "succes!";      
          else if [ $TRAVIS_BRANCH = "develop" ]; then
              echo "else";
          fi
    - stage: install2
      script: 
        - echo $TRAVIS_BRANCH
script:

before_deploy:

after_success:

