language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]


jobs:
  include:
    - stage: test1
      script: 
        - echo $TRAVIS_BUILD_NUMBER
    - script: 
        - echo $TRAVIS_TAG
    - stage: test2
      script: 
        - echo $TRAVIS_BRANCH
before_install:
  
install:  

script:

before_deploy:

after_success:

