language: node_js
node_js:
  - "lts/*"

#This caches $HOME/.npm or node_modules, depending on the repository’s structure.
cache: npm
    
# safelist
branches:
  only:
  - master  
  - develop  
#[skip <빌드스킵>]

jobs:
  include:
    - stage: test1
      script: 
        - echo $TRAVIS_TAG
    - script: 
        >  
      if  [ 1 = 1 ]; then
          echo "succes!";      
        else
          echo "else";
      fi
    - stage: test2
      script: 
        - echo $TRAVIS_BRANCH
before_install: 
install:  

script:
    - echo "succes!"
before_deploy:

after_success:

